# Generated by Django 4.2.3 on 2023-07-18 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_alter_quiz_questions_alter_quiz_result_ranges'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='genre',
            field=models.CharField(default='General', max_length=30),
        ),
    ]
