# Generated by Django 4.2.3 on 2023-07-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_quiz_genre'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['caption', 'genre'], name='quizapp_qui_caption_bb1bd7_idx'),
        ),
    ]
